---
abstract: 'Include stack traces on all warnings and errors'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  Cwd: '0'
  File::Spec: '0'
  File::Temp: '0'
  IPC::Open3: '0'
  Safe: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-Confess
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Scalar::Util: '0'
  perl: '5.006'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Devel-Confess
  license: http://dev.perl.org/licenses/
  repository: git://github.com/haarg/Devel-Confess
version: '0.009004'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
